### ISSUE TITLE
Remove use of deprecated classes ( post openBackhaul/ApplicationPattern#808 )

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/RequestSequenceRepresentation#72]
Parent change : https://github.com/openBackhaul/ApplicationPattern/issues/808

- remove use of deprecated classes ConfigurationInputWithMapping and LogicalTerminationPointWithMappingServices.
- remove unused function arguments from basic services

**Comment by PrathibaJee** [comment]
Since the latest AP version is 2.1.1 and the mentioned changes are specific to 2.0.1 closing this issue. Thanks.
